name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_NEW }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE_NEW }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa_new
          chmod 600 ~/.ssh/id_rsa_new
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa_new
          ssh-add -l  # List added keys for debugging

      - name: Deploy to DigitalOcean Droplet
        env:
          DO_USERNAME: ${{ secrets.DO_USERNAME }}
          DO_IP_ADDRESS: ${{ secrets.DO_IP_ADDRESS }}
        run: |
          ssh -T -o StrictHostKeyChecking=no $DO_USERNAME@$DO_IP_ADDRESS << EOF
          cd ~/bluewave-onboarding && git pull && docker compose down && docker compose build && docker compose up -d
          EOF
